files:
  - source: /src/_locales/en_US/messages.json
    translation: /src/_locales/%two_letters_code%/%original_file_name%
  - source: /locales/en_US/description.txt
    translation: /locales/%two_letters_code%/%original_file_name%
